# Release: https://github.com/scrtlabs/secretai-chatbot-2026/releases/tag/v0.0.1
# Workflow URL: https://github.com/scrtlabs/secretai-chatbot-2026/actions/runs/25159500479
# Commit: https://github.com/scrtlabs/secretai-chatbot-2026/commit/8561433317991b7348d941561ab8e7e04ce2bd18
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/secretai-chatbot-2026@sha256:d81b4132bcf13cd39e3804672d8ef695c87317990375d9c67122b4250f2e24ac
    ports:
      - '3000'
